# Generated by Django 5.1.1 on 2024-10-17 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_sitters', '0003_alter_petsitter_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='name',
            field=models.CharField(default='-', max_length=20),
            preserve_default=False,
        ),
    ]
