# Generated by Django 5.1.1 on 2024-10-17 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_sitters', '0007_alter_user_profile_picture_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address_house',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
