# Generated by Django 5.1.1 on 2024-10-19 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_sitters', '0008_alter_user_address_house'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(),
        ),
    ]
