# Generated by Django 5.1.1 on 2024-10-19 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_sitters', '0009_alter_user_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address_house',
            field=models.CharField(blank=True, default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture_url',
            field=models.URLField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
