# Generated by Django 5.1.1 on 2024-10-20 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_sitters', '0010_alter_user_address_house_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='breed',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='pet',
            name='info_special_treatment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='photo_URL',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet_sitters.petspecies'),
        ),
    ]
