# Generated by Django 5.1.1 on 2024-10-20 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_sitters', '0011_alter_pet_breed_alter_pet_info_special_treatment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='is_over',
            field=models.BooleanField(default=False),
        ),
    ]
