# Generated by Django 5.1.1 on 2024-10-20 15:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_sitters', '0013_alter_visit_rating_alter_visit_review_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='rating',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
